// <auto-generated />
namespace EProSeed.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMaxLengthToAll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMaxLengthToAll));
        
        string IMigrationMetadata.Id
        {
            get { return "201611180903220_AddMaxLengthToAll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
